/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CartLocalizedText;
import org.openapitools.client.model.CartMoney;
import org.openapitools.client.model.OptionImage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CartProductConfigurationStepOption
 */
public class CartProductConfigurationStepOptionTest {
    private final CartProductConfigurationStepOption model = new CartProductConfigurationStepOption();

    /**
     * Model tests for CartProductConfigurationStepOption
     */
    @Test
    public void testCartProductConfigurationStepOption() {
        // TODO: test CartProductConfigurationStepOption
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'grn'
     */
    @Test
    public void grnTest() {
        // TODO: test grn
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'priceVariation'
     */
    @Test
    public void priceVariationTest() {
        // TODO: test priceVariation
    }

    /**
     * Test the property 'weightVariation'
     */
    @Test
    public void weightVariationTest() {
        // TODO: test weightVariation
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'hasQuantity'
     */
    @Test
    public void hasQuantityTest() {
        // TODO: test hasQuantity
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
