/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CartLocalizedText;
import org.openapitools.client.model.CartMoney;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CartPaymentData
 */
public class CartPaymentDataTest {
    private final CartPaymentData model = new CartPaymentData();

    /**
     * Model tests for CartPaymentData
     */
    @Test
    public void testCartPaymentData() {
        // TODO: test CartPaymentData
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'vatAmount'
     */
    @Test
    public void vatAmountTest() {
        // TODO: test vatAmount
    }

    /**
     * Test the property 'vatPercentage'
     */
    @Test
    public void vatPercentageTest() {
        // TODO: test vatPercentage
    }

    /**
     * Test the property 'vatInaccurate'
     */
    @Test
    public void vatInaccurateTest() {
        // TODO: test vatInaccurate
    }

    /**
     * Test the property 'vatCalculated'
     */
    @Test
    public void vatCalculatedTest() {
        // TODO: test vatCalculated
    }

    /**
     * Test the property 'isUpfront'
     */
    @Test
    public void isUpfrontTest() {
        // TODO: test isUpfront
    }

}
