/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListCartsRequestFilter;
import org.openapitools.client.model.ListCartsRequestSort;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CartListCartsRequest
 */
public class CartListCartsRequestTest {
    private final CartListCartsRequest model = new CartListCartsRequest();

    /**
     * Model tests for CartListCartsRequest
     */
    @Test
    public void testCartListCartsRequest() {
        // TODO: test CartListCartsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'pageToken'
     */
    @Test
    public void pageTokenTest() {
        // TODO: test pageToken
    }

    /**
     * Test the property 'sorts'
     */
    @Test
    public void sortsTest() {
        // TODO: test sorts
    }

    /**
     * Test the property 'filterMask'
     */
    @Test
    public void filterMaskTest() {
        // TODO: test filterMask
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

}
