/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CartMoney;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CartPromotionData
 */
public class CartPromotionDataTest {
    private final CartPromotionData model = new CartPromotionData();

    /**
     * Model tests for CartPromotionData
     */
    @Test
    public void testCartPromotionData() {
        // TODO: test CartPromotionData
    }

    /**
     * Test the property 'promotionGrn'
     */
    @Test
    public void promotionGrnTest() {
        // TODO: test promotionGrn
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'cartItemIds'
     */
    @Test
    public void cartItemIdsTest() {
        // TODO: test cartItemIds
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'couponCode'
     */
    @Test
    public void couponCodeTest() {
        // TODO: test couponCode
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'vatAmount'
     */
    @Test
    public void vatAmountTest() {
        // TODO: test vatAmount
    }

    /**
     * Test the property 'vatPercentage'
     */
    @Test
    public void vatPercentageTest() {
        // TODO: test vatPercentage
    }

    /**
     * Test the property 'vatInaccurate'
     */
    @Test
    public void vatInaccurateTest() {
        // TODO: test vatInaccurate
    }

    /**
     * Test the property 'vatCalculated'
     */
    @Test
    public void vatCalculatedTest() {
        // TODO: test vatCalculated
    }

}
