/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CartListShipmentMethodsRequest
 */
public class CartListShipmentMethodsRequestTest {
    private final CartListShipmentMethodsRequest model = new CartListShipmentMethodsRequest();

    /**
     * Model tests for CartListShipmentMethodsRequest
     */
    @Test
    public void testCartListShipmentMethodsRequest() {
        // TODO: test CartListShipmentMethodsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'cartId'
     */
    @Test
    public void cartIdTest() {
        // TODO: test cartId
    }

}
