/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListCartsRequestFilterCartStatus;
import org.openapitools.client.model.ListCartsRequestFilterDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListCartsRequestFilter
 */
public class ListCartsRequestFilterTest {
    private final ListCartsRequestFilter model = new ListCartsRequestFilter();

    /**
     * Model tests for ListCartsRequestFilter
     */
    @Test
    public void testListCartsRequestFilter() {
        // TODO: test ListCartsRequestFilter
    }

    /**
     * Test the property 'searchTerms'
     */
    @Test
    public void searchTermsTest() {
        // TODO: test searchTerms
    }

    /**
     * Test the property 'customerEmails'
     */
    @Test
    public void customerEmailsTest() {
        // TODO: test customerEmails
    }

    /**
     * Test the property 'customerFirstnames'
     */
    @Test
    public void customerFirstnamesTest() {
        // TODO: test customerFirstnames
    }

    /**
     * Test the property 'customerLastnames'
     */
    @Test
    public void customerLastnamesTest() {
        // TODO: test customerLastnames
    }

    /**
     * Test the property 'customerPhones'
     */
    @Test
    public void customerPhonesTest() {
        // TODO: test customerPhones
    }

    /**
     * Test the property 'cartIds'
     */
    @Test
    public void cartIdsTest() {
        // TODO: test cartIds
    }

    /**
     * Test the property 'cartStatus'
     */
    @Test
    public void cartStatusTest() {
        // TODO: test cartStatus
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'agentGrn'
     */
    @Test
    public void agentGrnTest() {
        // TODO: test agentGrn
    }

}
