/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CartCartStatus;
import org.openapitools.client.model.CartCustomerData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateCartRequestPayload
 */
public class UpdateCartRequestPayloadTest {
    private final UpdateCartRequestPayload model = new UpdateCartRequestPayload();

    /**
     * Model tests for UpdateCartRequestPayload
     */
    @Test
    public void testUpdateCartRequestPayload() {
        // TODO: test UpdateCartRequestPayload
    }

    /**
     * Test the property 'cartStatus'
     */
    @Test
    public void cartStatusTest() {
        // TODO: test cartStatus
    }

    /**
     * Test the property 'customerData'
     */
    @Test
    public void customerDataTest() {
        // TODO: test customerData
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

}
