/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CartCartData;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Cart.JSON;

/**
 * CartListCartsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-21T15:21:28.271708366Z[Etc/UTC]")
public class CartListCartsResponse {
  public static final String SERIALIZED_NAME_CARTS = "carts";
  @SerializedName(SERIALIZED_NAME_CARTS)
  private List<CartCartData> carts;

  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "nextPageToken";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  private String nextPageToken;

  public CartListCartsResponse() {
  }

  public CartListCartsResponse carts(List<CartCartData> carts) {
    this.carts = carts;
    return this;
  }

  public CartListCartsResponse addCartsItem(CartCartData cartsItem) {
    if (this.carts == null) {
      this.carts = new ArrayList<>();
    }
    this.carts.add(cartsItem);
    return this;
  }

   /**
   * Get carts
   * @return carts
  **/
  @javax.annotation.Nullable
  public List<CartCartData> getCarts() {
    return carts;
  }

  public void setCarts(List<CartCartData> carts) {
    this.carts = carts;
  }


  public CartListCartsResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * Get nextPageToken
   * @return nextPageToken
  **/
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartListCartsResponse cartListCartsResponse = (CartListCartsResponse) o;
    return Objects.equals(this.carts, cartListCartsResponse.carts) &&
        Objects.equals(this.nextPageToken, cartListCartsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(carts, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartListCartsResponse {\n");
    sb.append("    carts: ").append(toIndentedString(carts)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("carts");
    openapiFields.add("nextPageToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CartListCartsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CartListCartsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CartListCartsResponse is not found in the empty JSON string", CartListCartsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CartListCartsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CartListCartsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("carts") != null && !jsonObj.get("carts").isJsonNull()) {
        JsonArray jsonArraycarts = jsonObj.getAsJsonArray("carts");
        if (jsonArraycarts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("carts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `carts` to be an array in the JSON string but got `%s`", jsonObj.get("carts").toString()));
          }

          // validate the optional field `carts` (array)
          for (int i = 0; i < jsonArraycarts.size(); i++) {
            CartCartData.validateJsonElement(jsonArraycarts.get(i));
          };
        }
      }
      if ((jsonObj.get("nextPageToken") != null && !jsonObj.get("nextPageToken").isJsonNull()) && !jsonObj.get("nextPageToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextPageToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPageToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CartListCartsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CartListCartsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CartListCartsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CartListCartsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CartListCartsResponse>() {
           @Override
           public void write(JsonWriter out, CartListCartsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CartListCartsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CartListCartsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CartListCartsResponse
  * @throws IOException if the JSON string is invalid with respect to CartListCartsResponse
  */
  public static CartListCartsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CartListCartsResponse.class);
  }

 /**
  * Convert an instance of CartListCartsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

