/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ListCartsRequestFilterCartStatus
 */
@JsonAdapter(ListCartsRequestFilterCartStatus.Adapter.class)
public enum ListCartsRequestFilterCartStatus {
  
  UNKNOWN("UNKNOWN"),
  
  ENABLED("ENABLED"),
  
  DISABLED("DISABLED");

  private String value;

  ListCartsRequestFilterCartStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ListCartsRequestFilterCartStatus fromValue(String value) {
    for (ListCartsRequestFilterCartStatus b : ListCartsRequestFilterCartStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ListCartsRequestFilterCartStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ListCartsRequestFilterCartStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ListCartsRequestFilterCartStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ListCartsRequestFilterCartStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ListCartsRequestFilterCartStatus.fromValue(value);
  }
}

