/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Cart.ApiException;
import org.openapitools.client.model.CartListPaymentMethodsRequest;
import org.openapitools.client.model.CartListPaymentMethodsResponse;
import org.openapitools.client.model.CartSetPaymentsRequest;
import org.openapitools.client.model.CartSetPaymentsResponse;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * List Payment Methods
     *
     * List payment methods
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPaymentMethodsTest() throws ApiException {
        CartListPaymentMethodsRequest body = null;
        CartListPaymentMethodsResponse response = api.listPaymentMethods(body);
        // TODO: test validations
    }

    /**
     * Set SetPayments
     *
     * Set SetPayments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setSetPaymentsTest() throws ApiException {
        CartSetPaymentsRequest body = null;
        CartSetPaymentsResponse response = api.setSetPayments(body);
        // TODO: test validations
    }

}
