/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Cart.ApiException;
import org.openapitools.client.model.CartApplyCouponsRequest;
import org.openapitools.client.model.CartRemoveCouponsRequest;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromotionsApi
 */
@Disabled
public class PromotionsApiTest {

    private final PromotionsApi api = new PromotionsApi();

    /**
     * Apply Coupons
     *
     * Apply coupons to the cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void applyCouponsTest() throws ApiException {
        CartApplyCouponsRequest body = null;
        Object response = api.applyCoupons(body);
        // TODO: test validations
    }

    /**
     * Remove Coupons
     *
     * Remove coupons from the cart
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeCouponsTest() throws ApiException {
        CartRemoveCouponsRequest body = null;
        Object response = api.removeCoupons(body);
        // TODO: test validations
    }

}
