/*
 * Cart Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_Cart.ApiException;
import org.openapitools.client.model.CartListShipmentMethodsRequest;
import org.openapitools.client.model.CartListShipmentMethodsResponse;
import org.openapitools.client.model.CartSetShipmentsRequest;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShipmentsApi
 */
@Disabled
public class ShipmentsApiTest {

    private final ShipmentsApi api = new ShipmentsApi();

    /**
     * List Shipment Methods
     *
     * List shipment methods
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listShipmentMethodsTest() throws ApiException {
        CartListShipmentMethodsRequest body = null;
        CartListShipmentMethodsResponse response = api.listShipmentMethods(body);
        // TODO: test validations
    }

    /**
     * Set Shipments
     *
     * Set shipments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setShipmentsTest() throws ApiException {
        CartSetShipmentsRequest body = null;
        Object response = api.setShipments(body);
        // TODO: test validations
    }

}
